### PR TITLE
feat: provision token dcentName property

### PR DESCRIPTION
**Pull request by 0xKheops**

### CODE REVIEW

**Review by alecdwm — APPROVED** [review]
LGTM!

---

If you're ready to merge this I can deploy the update to the prod squid

**Comment by 0xKheops** [comment]
@alecdwm yes i just tested locally it works.
looks like it's not needed to update the `talisman` repo dependencies to yesterday's PR, because dcentName property is stored in a generic `data` json field :)
please deploy when you have time

**Comment by alecdwm** [comment]
Deployed!

**Comment by 0xKheops** [comment]
Thanks! :heart:

**Pull request merged**
